### PR TITLE
[IOTA-22] [IOTA-23] 

### PR DESCRIPTION
**Pull request by shiv4nsh**
Rebased the new code and incorporated the changes for the jar name and moving project from spray to play
And hence fixed the issue https://issues.apache.org/jira/browse/IOTA-23?filter=-4&jql=project%20%3D%20IOTA%20ORDER%20BY%20createdDate%20DESC

### CODE REVIEW

**Comment by shiv4nsh** [comment]
@barbaragomes : Please review this pull request and let me know your concerns. I have rebased with the new code and made the changes and also please discard the pull request https://github.com/apache/incubator-iota/pull/6 as it is not mergable. Thanks !

**Comment by barbaragomes** [comment]
@shiv4nsh We apologize for the late response.

I understand that we haven't give you much details about this issue, my apologies.
We haven't accepted this PR because we are working on a better specification of the first steps to integrate play as well as some UI prototypes, so we can make this issue more clear.

We appreciate your contribution.

We will be updating this issue with more details soon.

Thanks.

**Comment by shiv4nsh** [comment]
@barbaragomes : Ok please provide the specifications of this ticket so that we can work efficiently on this ticket. Thanks !

**Comment by shiv4nsh** [comment]
@barbaragomes and @tonyfaustini : I have rebased the code and done the changes again , and have made the pull Request against it i.e #19 and #20 that contains changes for this PR and hence i am Closing this ! Please review those ! Thanks

**Pull request closed without merging**
