### PR TITLE
[IOTA-29]

### PR DESCRIPTION
**Pull request by shiv4nsh**
Removed the scalastyle warnings and removed the usage of var at some places wherever it was possible.

### CODE REVIEW

**Comment by shiv4nsh** [comment]
@barbaragomes :Could you please review this PR and merge it. If you merge the pull Request #16 then I have to re implement the whole functionality.

**Comment by shiv4nsh** [comment]
@tonyfaustini @asfgit : I will rebase this and make a new PR for this !

**Comment by tonyLitBit** [comment]
Thanks

**Comment by shiv4nsh** [comment]
@tonyLitBit : Just wanted to know , what are we planning to implement ahead ! What I mean is where are we heading and when is the due date of the first release !

**Pull request closed without merging**
