### PR TITLE
[IOTA-21]

### PR DESCRIPTION
**Pull request by phalodi**
Refactor the built to manage dependencies in more efficient way and add scalastyle plugin for code quality.

### CODE REVIEW

**Comment by phalodi** [comment]
@barbaragomes can you once review it and give comment on PR

**Comment by phalodi** [comment]
https://issues.apache.org/jira/browse/IOTA-21

**Comment by barbaragomes** [comment]
Thanks @phalodi.

**Comment by barbaragomes** [comment]
Taking a quick look I found one issue:

1. `val ZMQDependecies = provided(akka_actor, zmq, fey)` the `zmq` dependence should not be `provided`

**Comment by phalodi** [comment]
@barbaragomes thanks for the comment its should be compile time right?

**Comment by barbaragomes** [comment]
Exactly

**Comment by phalodi** [comment]
@barbaragomes i fix it and push you can review it.

**Comment by barbaragomes** [comment]
@phalodi My apologies, but I'm not sure if it should be `runtime`. The `compile` configuration will make the dependency also available in `runtime`?

**Comment by phalodi** [comment]
@barbaragomes yess compile dependency will also available at runtime and test in both.

**Comment by barbaragomes** [comment]
@phalodi PR has been tested and will be merged once you, please, submit the following modifications:

1. `BuildSettings`: change `organization := "com.libit"` to `organization := "org.apache.iota"`
2. Remove all reference to the fey project since this folder is not actually a SBT project, like for example `lazy val fey = Project(` and `aggregate = Seq(Stream, ZMQ,fey)`
3. `PerformersBuild`: Remove `stream` and `zmq` from `mainClass := Some`

I understand that some of the requested changes were part of the first SBT Build.scala but it would be nice if we could have all of them in the same PR since we are refactoring it =)

Thanks

**Comment by phalodi** [comment]
@barbaragomes I make changes and push it once review it and give comment if needed.

**Comment by barbaragomes** [comment]
@phalodi Can you please change the organization name for all of the projects?

**Comment by phalodi** [comment]
@barbaragomes I remove fey setting from build settings and also add organization name to basic setting so every project have it.

**Comment by barbaragomes** [comment]
@phalodi Thank you! We will be merging it soon.

**Pull request merged**
