### PR TITLE
[IOTA-23] Rebased the Code and converted the spray Routes to the play Routes

### PR DESCRIPTION
**Pull request by shiv4nsh**
In this PR in have incorporated the changes so that the Play routes will be used instead of the spray Routes.
This PR along with #19 will have all the changes for  #6 and #8 . Hence we can close #6 and #8 .

### CODE REVIEW

**Comment by tonyLitBit** [comment]
The end point monitoringevents is not working as expected it is supposed to render the html table but instead it is displaying the source code

**Comment by shiv4nsh** [comment]
@tonyfaustini : Nice Catch ! I have made the required changes and now it looks like this 
monitoring evebts

**Comment by tonyLitBit** [comment]
Can you please add the configuration to the utils.scala file in the config object

**Comment by shiv4nsh** [comment]
@tonyLitBit : I have done the Changes , please review it Thanks !

**Comment by shiv4nsh** [comment]
@tonyfaustini : Can we merge this now ?

**Comment by barbaragomes** [comment]
@shiv4nsh Everything looks good to me. Thank you for the fixes.

@tonyLitBit Could you please merge this PR?

**Pull request merged**
